import Head from 'next/head'
import styled from '@emotion/styled'
import css from '@styled-system/css'
import { useCallback, useState } from 'react'
import Flex from '../components/primitives/Flex'
import Box from '../components/primitives/Box'
import Stack from '../components/elements/Stack'
import Heading from '../components/elements/Heading'
import Image from 'next/image'
import Type from '../components/elements/Type'
import ChevronUpIcon from '../components/icons/ChevronUpIcon'
import ChevronDownIcon from '../components/icons/ChevronDownIcon'
import Grid from '../components/primitives/Grid'
import Button from '../components/elements/Button'
import Link from 'next/link'
import GitHubIcon from '../components/icons/GitHubIcon'
import IconButton from '../components/elements/IconButton'

const panel = {
  open: 'translate3d(0, 0, 0)',
  closed: 'translate3d(0, calc(100% - 170px), 0)',
}

const Card = styled(Flex)(
  css({
    flexDirection: 'column',
    width: '100%',
    cursor: 'pointer',
    img: {
      transition: 'transform 0.15s',
    },
    '&:hover img': {
      transform: 'scale(1.1)',
    },
  }),
)

export default function Home() {
  const [isOpen, setIsOpen] = useState(false)

  const togglePanel = useCallback(() => {
    setIsOpen(!isOpen)
  }, [isOpen, setIsOpen])

  return (
    <>
      <Head>
        <title>Rod Levtion - UI Developer &amp; Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex as="main" flex={1}>
        <Box
          bg="background.alpha.css"
          width={{ _: '100%', lg: 460, xl: 540, xxl: 660 }}
          height={{ _: '100%', lg: 'auto' }}
          px={{ _: 'md', lg: 'xl' }}
          py={{ _: 'md', lg: 'lg' }}
          position={{ _: 'fixed', lg: 'static' }}
          borderTopLeftRadius={{ _: 'lg', lg: 0 }}
          borderTopRightRadius={{ _: 'lg', lg: 0 }}
          boxShadow={{ _: 'inverse.md', lg: 'none' }}
          transition={{
            _: 'transform 0.3s cubic-bezier(0.280, 0.840, 0.420, 1.1)',
            lg: 'none',
          }}
          transform={{ _: isOpen ? panel.open : panel.closed, lg: 'none' }}
          zIndex={10}
        >
          <Stack spacing="lg">
            <Flex
              role="button"
              display={{ _: 'flex', lg: 'none' }}
              alignItems="center"
              justifyContent="center"
              onClick={togglePanel}
              p="md"
            >
              {!isOpen && (
                <ChevronUpIcon size="md" color="typography.default" />
              )}
              {isOpen && (
                <ChevronDownIcon size="md" color="typography.default" />
              )}
            </Flex>
            <Box boxShadow="lg" width={200} height={200} borderRadius="lg">
              <Box width={200} height={200} borderRadius="lg" overflow="hidden">
                <Image
                  alt="Rod Leviton - Profile Image"
                  src="/images/rod_leviton_profile.png"
                  loading="lazy"
                  quality={100}
                  width={200}
                  height={200}
                />
              </Box>
            </Box>
            <Stack spacing="xs">
              <Heading
                level="2"
                size="xxs"
                fontWeight="semibold"
                textTransform="uppercase"
                opacity={0.5}
              >
                UI Developer &amp; Designer
              </Heading>
              <Heading level="1">Rod Leviton</Heading>
              <IconButton
                variant="secondary"
                href="https://github.com/rodleviton"
                target="_blank"
              >
                <GitHubIcon color="typography.default" size="lg" />
              </IconButton>
            </Stack>

            <Stack spacing="lg">
              <Box bg="background.beta.css" height={4} width="100%"></Box>
              <Type>
                I am an experienced software engineer by day with a diverse
                range of skills and experience that I have acquired throughout
                my 10+ years as a software engineer. I take great pleasure in
                continually learning new skills, frameworks and libraries which
                has enabled me to stay up-to-date with the ever evolving digital
                development and design space.
              </Type>
              <Type>
                What I believe sets me apart from other developers in my field
                is my design consideration, aesthetics and ability to
                technically execute a well implemented solution. Being a part of
                the entire life-cycle from concept to completion is a role I
                take great pride in and my previous experience history supports
                this.
              </Type>
              <Box bg="background.beta.css" height={4} width="100%"></Box>
            </Stack>
          </Stack>
        </Box>
        <Flex
          flex="1"
          bg="background.beta.css"
          px={{ _: 'md', lg: 'xl' }}
          py={{ _: 'md', lg: 'lg' }}
          pb={{ _: 100, lg: 'lg' }}
        >
          <Box width="100%">
            <Grid
              gridGap="xl"
              gridTemplateColumns="repeat(auto-fit, minmax(300px, 340px))"
            >
              <Link href="/pixels/vue-card-stack" passHref>
                <Card>
                  <Stack
                    spacing="lg"
                    width="100%"
                    gridAutoRows="min-content"
                    mb="lg"
                  >
                    <Box boxShadow="lg" borderRadius="lg">
                      <Box
                        borderRadius="lg"
                        overflow="hidden"
                        position="relative"
                      >
                        <Image
                          alt="Card Stack - Title Image"
                          src="/images/pixels/card_stack_title.png"
                          loading="lazy"
                          quality={100}
                          layout="responsive"
                          width={360}
                          height={220}
                        />
                      </Box>
                    </Box>
                    <Stack>
                      <Stack spacing="xs">
                        <Heading
                          level="5"
                          size="xxs"
                          fontWeight="semibold"
                          textTransform="uppercase"
                          opacity={0.5}
                        >
                          Open Source
                        </Heading>
                        <Heading level="2">Card Stack</Heading>
                      </Stack>
                      <Type>
                        Stackable, swipeable, tweakable Vue card component.
                      </Type>
                    </Stack>
                  </Stack>
                  <Flex
                    flexGrow={1}
                    flexDirection="column"
                    justifyContent="flex-end"
                  >
                    <Button width={{ _: '100%', md: 260 }}>View</Button>
                  </Flex>
                </Card>
              </Link>

              <Link href="/pixels/oberhauser-calendar" passHref>
                <Card>
                  <Stack
                    spacing="lg"
                    width="100%"
                    gridAutoRows="min-content"
                    mb="lg"
                  >
                    <Box boxShadow="lg" borderRadius="lg">
                      <Box
                        borderRadius="lg"
                        overflow="hidden"
                        position="relative"
                      >
                        <Image
                          alt="Oberhauser Kalendar - Title Image"
                          src="/images/pixels/oberhauser_calendar_title.png"
                          loading="lazy"
                          quality={100}
                          layout="responsive"
                          width={360}
                          height={220}
                        />
                      </Box>
                    </Box>
                    <Stack>
                      <Stack spacing="xs">
                        <Heading
                          level="5"
                          size="xxs"
                          fontWeight="semibold"
                          textTransform="uppercase"
                          opacity={0.5}
                        >
                          Open Source
                        </Heading>
                        <Heading level="2">Oberhauser Calendar</Heading>
                      </Stack>
                      <Type>
                        Beautiful calendar concept inspired by the work of
                        Bureau Oberhaeuser.
                      </Type>
                    </Stack>
                  </Stack>
                  <Flex
                    flexGrow={1}
                    flexDirection="column"
                    justifyContent="flex-end"
                  >
                    <Button width={{ _: '100%', md: 260 }}>View</Button>
                  </Flex>
                </Card>
              </Link>
            </Grid>
          </Box>
        </Flex>
      </Flex>
    </>
  )
}
